[project]
name = "hedonism-who-dis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery[redis]>=5.6.3",
    "deepface>=0.0.100",
    "tf-keras>=2.21.0",
    "gql[all]>=4.0.0",
    "transformers>=5.10.2",
    "torch>=2.12.0",
    "accelerate>=1.13.0",
]

[dependency-groups]
dev = [
    "pyrefly>=0.60.0",
    "celery-types>=0.26.0",
    "pytest>=8.0.0",
    "pandas-stubs~=3.0.3",
]
